# Generated by Django 5.2.1 on 2025-10-19 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoinventario',
            name='realizado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tienda.empleado'),
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.ManyToManyField(blank=True, to='inventario.categoria'),
        ),
        migrations.AddField(
            model_name='producto',
            name='dueño',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='tienda.empleado'),
        ),
        migrations.AddField(
            model_name='producto',
            name='registrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_registrados', to='tienda.empleado'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='inventario.producto'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventarios', to='inventario.producto'),
        ),
        migrations.AddField(
            model_name='producto',
            name='temporada',
            field=models.ManyToManyField(blank=True, related_name='productos', to='inventario.temporada'),
        ),
        migrations.AddField(
            model_name='transferenciainventario',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto'),
        ),
        migrations.AddField(
            model_name='transferenciainventario',
            name='realizado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tienda.empleado'),
        ),
        migrations.AddField(
            model_name='transferenciainventario',
            name='destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_destino', to='inventario.ubicacion'),
        ),
        migrations.AddField(
            model_name='transferenciainventario',
            name='origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_origen', to='inventario.ubicacion'),
        ),
        migrations.AddField(
            model_name='producto',
            name='ubicacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='inventario.ubicacion'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_destino', to='inventario.ubicacion'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_origen', to='inventario.ubicacion'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.ubicacion'),
        ),
        migrations.AddField(
            model_name='valoratributo',
            name='atributo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.atributo'),
        ),
        migrations.AddField(
            model_name='valoratributo',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores_atributo', to='inventario.producto'),
        ),
        migrations.AlterUniqueTogether(
            name='categoria',
            unique_together={('nombre', 'padre')},
        ),
        migrations.AlterUniqueTogether(
            name='atributo',
            unique_together={('nombre', 'categoria')},
        ),
        migrations.AlterUniqueTogether(
            name='inventario',
            unique_together={('producto', 'ubicacion')},
        ),
        migrations.AlterUniqueTogether(
            name='valoratributo',
            unique_together={('producto', 'atributo')},
        ),
    ]
