# Generated by Django 5.2.1 on 2025-11-07 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_producto_codigo_barras_producto_tipo_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='tipo_codigo',
            field=models.CharField(blank=True, choices=[('code128', 'Code 128'), ('code39', 'Code 39'), ('ean13', 'EAN-13'), ('ean14', 'EAN-14'), ('itf14', 'ITF-14'), ('datamatrix', 'DataMatrix')], help_text='Tipo de código de barras usado', max_length=20, null=True, unique=True),
        ),
    ]
