# Generated by Django 5.2.1 on 2025-11-07 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_alter_producto_codigo_barras_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='ubicacion',
        ),
    ]
