# Generated by Django 5.2.1 on 2025-11-08 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_remove_producto_ubicacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventario',
            old_name='cantidad',
            new_name='cantidad_actual',
        ),
    ]
