# Generated by Django 5.2.1 on 2025-11-22 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_rename_cantidad_inventario_cantidad_actual'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoinventario',
            name='motivo',
            field=models.CharField(blank=True, choices=[('devolucion', 'Devolución de cliente'), ('compra', 'Compra a proveedor'), ('reabastecimiento', 'Reabastecimiento interno'), ('nuevo', 'Nuevo producto'), ('venta', 'Venta'), ('daño', 'Daño'), ('perdida', 'Pérdida'), ('correccion', 'Corrección de inventario'), ('conteo', 'Conteo físico')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='tipo',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida'), ('transferencia', 'Transferencia'), ('ajuste', 'Ajuste')], max_length=20),
        ),
    ]
