# Generated by Django 5.2.1 on 2025-11-30 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_remove_producto_categoria_producto_categoria'),
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transferenciainventario',
            options={'ordering': ['-fecha'], 'verbose_name': 'Transferencia de Inventario', 'verbose_name_plural': 'Transferencias de Inventario'},
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='transferencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='inventario.transferenciainventario'),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='tipo',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida'), ('ajuste', 'Ajuste')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transferenciainventario',
            name='realizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tienda.empleado'),
        ),
    ]
