# Generated by Django 5.2.1 on 2025-11-30 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_alter_transferenciainventario_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventarios', to='inventario.ubicacion'),
        ),
    ]
